# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: bel-amri <clorensunity@gmail.com>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2023/06/02 16:45:04 by bel-amri          #+#    #+#              #
#    Updated: 2023/06/03 14:54:50 by bel-amri         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

all:
	c++ main.cpp Harl.cpp -std=c++98 -Wall -Wextra -Werror -o "Harl filter" && ./"Harl filter" ERROR